fix fractl-lein-template typo (#1152)

diff --git a/bin/fractl b/bin/fractl
--- a/bin/fractl
+++ b/bin/fractl
@@ -107,7 +107,7 @@ function self_install {
       exit 1
   fi
   local templ_dir="$FRACTL_HOME/self-installs/fractl-lein-template"
-  git clone https://github.com/fractl-io/fractl-lein-tempate.git "$templ_dir" || echo "ERROR: failed to clone fractl-lein-template"; return
+  git clone https://github.com/fractl-io/fractl-lein-template.git "$templ_dir" || echo "ERROR: failed to clone fractl-lein-template"; return
   cd "$templ_dir/fractl-model"
   lein install || echo "ERROR: failed to install fractl-lein-template"
   cd -
