clone/install lein-template. swicth to current-component in repl

diff --git a/bin/fractl b/bin/fractl
--- a/bin/fractl
+++ b/bin/fractl
@@ -106,6 +106,11 @@ function self_install {
       download_failed_message "$FRACTL_URL" "$exit_code"
       exit 1
   fi
+  local templ_dir="$FRACTL_HOME/self-installs/fractl-lein-template"
+  git clone https://github.com/fractl-io/fractl-lein-tempate.git "$templ_dir" || echo "ERROR: failed to clone fractl-lein-template"; return
+  cd "$templ_dir/fractl-model"
+  lein install || echo "ERROR: failed to install fractl-lein-template"
+  cd -
 }
 
 
